#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XFitWatchface.Resource", IsApplication=true)]

namespace XFitWatchface
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int generic_confirmation_generic_confirmation_animation = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int generic_confirmation_icon_animation = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int open_on_phone_arrow_animation = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int open_on_phone_path_1_animation = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int open_on_phone_path_2_animation = 2131034116;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f060000
			public const int circular_image_button_anim = 2131099648;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0d0000
			public const int progress_spinner_sequence = 2131558400;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010010
			public const int ambientEnabled = 2130771984;
			
			// aapt resource value: 0x7f010025
			public const int buttonRippleColor = 2130772005;
			
			// aapt resource value: 0x7f010011
			public const int buttonSize = 2130771985;
			
			// aapt resource value: 0x7f010001
			public const int cameraBearing = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cameraTargetLat = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cameraTargetLng = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int cameraTilt = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cameraZoom = 2130771973;
			
			// aapt resource value: 0x7f010016
			public const int circleCrop = 2130771990;
			
			// aapt resource value: 0x7f01001e
			public const int circle_border_color = 2130771998;
			
			// aapt resource value: 0x7f01001d
			public const int circle_border_width = 2130771997;
			
			// aapt resource value: 0x7f01001a
			public const int circle_color = 2130771994;
			
			// aapt resource value: 0x7f01001f
			public const int circle_padding = 2130771999;
			
			// aapt resource value: 0x7f01001b
			public const int circle_radius = 2130771995;
			
			// aapt resource value: 0x7f01001c
			public const int circle_radius_pressed = 2130771996;
			
			// aapt resource value: 0x7f010040
			public const int circular_layout_gravity = 2130772032;
			
			// aapt resource value: 0x7f010041
			public const int circular_text_size = 2130772033;
			
			// aapt resource value: 0x7f010012
			public const int colorScheme = 2130771986;
			
			// aapt resource value: 0x7f010035
			public const int color_sequence = 2130772021;
			
			// aapt resource value: 0x7f01002b
			public const int dotColor = 2130772011;
			
			// aapt resource value: 0x7f01002c
			public const int dotColorSelected = 2130772012;
			
			// aapt resource value: 0x7f010030
			public const int dotFadeInDuration = 2130772016;
			
			// aapt resource value: 0x7f01002e
			public const int dotFadeOutDelay = 2130772014;
			
			// aapt resource value: 0x7f01002f
			public const int dotFadeOutDuration = 2130772015;
			
			// aapt resource value: 0x7f01002d
			public const int dotFadeWhenIdle = 2130772013;
			
			// aapt resource value: 0x7f010029
			public const int dotRadius = 2130772009;
			
			// aapt resource value: 0x7f01002a
			public const int dotRadiusSelected = 2130772010;
			
			// aapt resource value: 0x7f010031
			public const int dotShadowColor = 2130772017;
			
			// aapt resource value: 0x7f010033
			public const int dotShadowDx = 2130772019;
			
			// aapt resource value: 0x7f010034
			public const int dotShadowDy = 2130772020;
			
			// aapt resource value: 0x7f010032
			public const int dotShadowRadius = 2130772018;
			
			// aapt resource value: 0x7f010028
			public const int dotSpacing = 2130772008;
			
			// aapt resource value: 0x7f010015
			public const int imageAspectRatio = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int imageAspectRatioAdjust = 2130771988;
			
			// aapt resource value: 0x7f010024
			public const int imageScaleMode = 2130772004;
			
			// aapt resource value: 0x7f010021
			public const int image_circle_percentage = 2130772001;
			
			// aapt resource value: 0x7f010022
			public const int image_horizontal_offcenter_percentage = 2130772002;
			
			// aapt resource value: 0x7f010023
			public const int image_tint = 2130772003;
			
			// aapt resource value: 0x7f010042
			public const int layoutManager = 2130772034;
			
			// aapt resource value: 0x7f010019
			public const int layout_box = 2130771993;
			
			// aapt resource value: 0x7f010038
			public const int layout_gravityRound = 2130772024;
			
			// aapt resource value: 0x7f01003a
			public const int layout_heightRound = 2130772026;
			
			// aapt resource value: 0x7f01003f
			public const int layout_marginBottomRound = 2130772031;
			
			// aapt resource value: 0x7f01003c
			public const int layout_marginLeftRound = 2130772028;
			
			// aapt resource value: 0x7f01003e
			public const int layout_marginRightRound = 2130772030;
			
			// aapt resource value: 0x7f01003b
			public const int layout_marginRound = 2130772027;
			
			// aapt resource value: 0x7f01003d
			public const int layout_marginTopRound = 2130772029;
			
			// aapt resource value: 0x7f010039
			public const int layout_widthRound = 2130772025;
			
			// aapt resource value: 0x7f010006
			public const int liteMode = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int mapType = 2130771968;
			
			// aapt resource value: 0x7f010018
			public const int maxTextSize = 2130771992;
			
			// aapt resource value: 0x7f010017
			public const int minTextSize = 2130771991;
			
			// aapt resource value: 0x7f010026
			public const int pressedButtonTranslationZ = 2130772006;
			
			// aapt resource value: 0x7f010036
			public const int rectLayout = 2130772022;
			
			// aapt resource value: 0x7f010044
			public const int reverseLayout = 2130772036;
			
			// aapt resource value: 0x7f010037
			public const int roundLayout = 2130772023;
			
			// aapt resource value: 0x7f010013
			public const int scopeUris = 2130771987;
			
			// aapt resource value: 0x7f010020
			public const int shadow_width = 2130772000;
			
			// aapt resource value: 0x7f010043
			public const int spanCount = 2130772035;
			
			// aapt resource value: 0x7f010045
			public const int stackFromEnd = 2130772037;
			
			// aapt resource value: 0x7f010007
			public const int uiCompass = 2130771975;
			
			// aapt resource value: 0x7f01000f
			public const int uiMapToolbar = 2130771983;
			
			// aapt resource value: 0x7f010008
			public const int uiRotateGestures = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int uiScrollGestures = 2130771977;
			
			// aapt resource value: 0x7f01000a
			public const int uiTiltGestures = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int uiZoomControls = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int uiZoomGestures = 2130771980;
			
			// aapt resource value: 0x7f010027
			public const int update_interval = 2130772007;
			
			// aapt resource value: 0x7f01000d
			public const int useViewLifecycle = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int zOrderOnTop = 2130771982;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090038
			public const int ColorItemCircleBorderColor = 2131296312;
			
			// aapt resource value: 0x7f090037
			public const int ColorItemLabelColor = 2131296311;
			
			// aapt resource value: 0x7f090033
			public const int ConfigActivityBackground = 2131296307;
			
			// aapt resource value: 0x7f090036
			public const int ConfigActivityCircleBorderColor = 2131296310;
			
			// aapt resource value: 0x7f090034
			public const int ConfigActivityHeaderTextColor = 2131296308;
			
			// aapt resource value: 0x7f090035
			public const int ConfigActivityItemLabelColor = 2131296309;
			
			// aapt resource value: 0x7f090017
			public const int action_button_background = 2131296279;
			
			// aapt resource value: 0x7f090018
			public const int black = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int black_54p = 2131296281;
			
			// aapt resource value: 0x7f09001a
			public const int black_86p = 2131296282;
			
			// aapt resource value: 0x7f09001b
			public const int blue = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int card_default_background = 2131296284;
			
			// aapt resource value: 0x7f090039
			public const int circular_button = 2131296313;
			
			// aapt resource value: 0x7f09001d
			public const int circular_button_disabled = 2131296285;
			
			// aapt resource value: 0x7f09001e
			public const int circular_button_normal = 2131296286;
			
			// aapt resource value: 0x7f09001f
			public const int circular_button_pressed = 2131296287;
			
			// aapt resource value: 0x7f09000e
			public const int common_action_bar_splitter = 2131296270;
			
			// aapt resource value: 0x7f09003a
			public const int common_google_signin_btn_text_dark = 2131296314;
			
			// aapt resource value: 0x7f09000f
			public const int common_google_signin_btn_text_dark_default = 2131296271;
			
			// aapt resource value: 0x7f090011
			public const int common_google_signin_btn_text_dark_disabled = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int common_google_signin_btn_text_dark_focused = 2131296274;
			
			// aapt resource value: 0x7f090010
			public const int common_google_signin_btn_text_dark_pressed = 2131296272;
			
			// aapt resource value: 0x7f09003b
			public const int common_google_signin_btn_text_light = 2131296315;
			
			// aapt resource value: 0x7f090013
			public const int common_google_signin_btn_text_light_default = 2131296275;
			
			// aapt resource value: 0x7f090015
			public const int common_google_signin_btn_text_light_disabled = 2131296277;
			
			// aapt resource value: 0x7f090016
			public const int common_google_signin_btn_text_light_focused = 2131296278;
			
			// aapt resource value: 0x7f090014
			public const int common_google_signin_btn_text_light_pressed = 2131296276;
			
			// aapt resource value: 0x7f09003c
			public const int common_plus_signin_btn_text_dark = 2131296316;
			
			// aapt resource value: 0x7f090006
			public const int common_plus_signin_btn_text_dark_default = 2131296262;
			
			// aapt resource value: 0x7f090008
			public const int common_plus_signin_btn_text_dark_disabled = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int common_plus_signin_btn_text_dark_focused = 2131296265;
			
			// aapt resource value: 0x7f090007
			public const int common_plus_signin_btn_text_dark_pressed = 2131296263;
			
			// aapt resource value: 0x7f09003d
			public const int common_plus_signin_btn_text_light = 2131296317;
			
			// aapt resource value: 0x7f09000a
			public const int common_plus_signin_btn_text_light_default = 2131296266;
			
			// aapt resource value: 0x7f09000c
			public const int common_plus_signin_btn_text_light_disabled = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int common_plus_signin_btn_text_light_focused = 2131296269;
			
			// aapt resource value: 0x7f09000b
			public const int common_plus_signin_btn_text_light_pressed = 2131296267;
			
			// aapt resource value: 0x7f090020
			public const int dark_blue = 2131296288;
			
			// aapt resource value: 0x7f090021
			public const int dark_grey = 2131296289;
			
			// aapt resource value: 0x7f090022
			public const int dark_red = 2131296290;
			
			// aapt resource value: 0x7f090023
			public const int dialog_background = 2131296291;
			
			// aapt resource value: 0x7f090024
			public const int dialog_shade_background = 2131296292;
			
			// aapt resource value: 0x7f090025
			public const int disabled_text_light = 2131296293;
			
			// aapt resource value: 0x7f090026
			public const int dismiss_close = 2131296294;
			
			// aapt resource value: 0x7f090027
			public const int dismiss_close_pressed = 2131296295;
			
			// aapt resource value: 0x7f090028
			public const int dismiss_overlay_bg = 2131296296;
			
			// aapt resource value: 0x7f090029
			public const int green = 2131296297;
			
			// aapt resource value: 0x7f09002a
			public const int grey = 2131296298;
			
			// aapt resource value: 0x7f09002b
			public const int light_grey = 2131296299;
			
			// aapt resource value: 0x7f09002c
			public const int orange = 2131296300;
			
			// aapt resource value: 0x7f090002
			public const int place_autocomplete_prediction_primary_text = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int place_autocomplete_prediction_primary_text_highlight = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int place_autocomplete_prediction_secondary_text = 2131296260;
			
			// aapt resource value: 0x7f090001
			public const int place_autocomplete_search_hint = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int place_autocomplete_search_text = 2131296256;
			
			// aapt resource value: 0x7f090005
			public const int place_autocomplete_separator = 2131296261;
			
			// aapt resource value: 0x7f09002d
			public const int primary_text_dark = 2131296301;
			
			// aapt resource value: 0x7f09002e
			public const int primary_text_light = 2131296302;
			
			// aapt resource value: 0x7f09002f
			public const int red = 2131296303;
			
			// aapt resource value: 0x7f090030
			public const int secondary_text_light = 2131296304;
			
			// aapt resource value: 0x7f090031
			public const int semitransparent_grey = 2131296305;
			
			// aapt resource value: 0x7f090032
			public const int white = 2131296306;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a001d
			public const int ContentPaddingStart = 2131361821;
			
			// aapt resource value: 0x7f0a001c
			public const int StepCountOffset = 2131361820;
			
			// aapt resource value: 0x7f0a001b
			public const int StepCountTextSize = 2131361819;
			
			// aapt resource value: 0x7f0a000a
			public const int card_content_padding_rect_top = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int circular_button_elevation = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int circular_button_elevation_pressed = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int close_button_diameter = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int diag_button_bottom_padding = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int diag_button_bottom_padding_round = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int diag_button_side_padding_right_round = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int diag_content_bottom_padding = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int diag_content_side_padding = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int diag_content_side_padding_round = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int diag_content_top_padding = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public const int diag_content_top_padding_round = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int diag_floating_height = 2131361814;
			
			// aapt resource value: 0x7f0a0017
			public const int diag_shade_height_rect = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int diag_shade_height_round = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int dismiss_padding = 2131361817;
			
			// aapt resource value: 0x7f0a001a
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131361818;
			
			// aapt resource value: 0x7f0a0000
			public const int place_autocomplete_button_padding = 2131361792;
			
			// aapt resource value: 0x7f0a0008
			public const int place_autocomplete_powered_by_google_height = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int place_autocomplete_powered_by_google_start = 2131361801;
			
			// aapt resource value: 0x7f0a0003
			public const int place_autocomplete_prediction_height = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int place_autocomplete_prediction_horizontal_margin = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int place_autocomplete_prediction_primary_text = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int place_autocomplete_prediction_secondary_text = 2131361798;
			
			// aapt resource value: 0x7f0a0002
			public const int place_autocomplete_progress_horizontal_margin = 2131361794;
			
			// aapt resource value: 0x7f0a0001
			public const int place_autocomplete_progress_size = 2131361793;
			
			// aapt resource value: 0x7f0a0007
			public const int place_autocomplete_separator_start = 2131361799;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int card_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int card_frame = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int card_frame_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int close_button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_full_open_on_phone = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_dark_disabled = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_dark_focused = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_dark_normal = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_dark_pressed = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_icon_light_disabled = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_icon_light_focused = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_icon_light_normal = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_icon_light_pressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_dark_disabled = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_dark_focused = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_dark_normal = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_dark_pressed = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_google_signin_btn_text_light_disabled = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_google_signin_btn_text_light_focused = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_google_signin_btn_text_light_normal = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_google_signin_btn_text_light_pressed = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_ic_googleplayservices = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_dark_focused = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_dark_normal = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_icon_light_disabled = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_icon_light_focused = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_icon_light_normal = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_icon_light_pressed = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_dark_disabled = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_dark_focused = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_dark_normal = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_dark_pressed = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int common_plus_signin_btn_text_light_disabled = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int common_plus_signin_btn_text_light_focused = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int common_plus_signin_btn_text_light_normal = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int common_plus_signin_btn_text_light_pressed = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int generic_confirmation = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int generic_confirmation_animation = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_full_cancel = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_full_sad = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int open_on_phone = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int open_on_phone_animation = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int places_ic_clear = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int places_ic_search = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int powered_by_google_dark = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int powered_by_google_light = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int preview_xfit = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int XamarinWatchFaceBackground = 2130837561;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0f0034
			public const int Circle = 2131689524;
			
			// aapt resource value: 0x7f0f0033
			public const int ColorPicker = 2131689523;
			
			// aapt resource value: 0x7f0f0031
			public const int Content = 2131689521;
			
			// aapt resource value: 0x7f0f0032
			public const int Header = 2131689522;
			
			// aapt resource value: 0x7f0f0035
			public const int Label = 2131689525;
			
			// aapt resource value: 0x7f0f000c
			public const int adjust_height = 2131689484;
			
			// aapt resource value: 0x7f0f000d
			public const int adjust_width = 2131689485;
			
			// aapt resource value: 0x7f0f0020
			public const int alertTitle = 2131689504;
			
			// aapt resource value: 0x7f0f000e
			public const int all = 2131689486;
			
			// aapt resource value: 0x7f0f001f
			public const int animatedWrapperContainer = 2131689503;
			
			// aapt resource value: 0x7f0f0009
			public const int auto = 2131689481;
			
			// aapt resource value: 0x7f0f000f
			public const int bottom = 2131689487;
			
			// aapt resource value: 0x7f0f0021
			public const int buttonPanel = 2131689505;
			
			// aapt resource value: 0x7f0f0013
			public const int center = 2131689491;
			
			// aapt resource value: 0x7f0f0015
			public const int center_horizontal = 2131689493;
			
			// aapt resource value: 0x7f0f0016
			public const int center_vertical = 2131689494;
			
			// aapt resource value: 0x7f0f0017
			public const int clip_horizontal = 2131689495;
			
			// aapt resource value: 0x7f0f0018
			public const int clip_vertical = 2131689496;
			
			// aapt resource value: 0x7f0f000a
			public const int dark = 2131689482;
			
			// aapt resource value: 0x7f0f0023
			public const int dismiss_overlay_button = 2131689507;
			
			// aapt resource value: 0x7f0f0022
			public const int dismiss_overlay_explain = 2131689506;
			
			// aapt resource value: 0x7f0f0019
			public const int end = 2131689497;
			
			// aapt resource value: 0x7f0f001a
			public const int fill = 2131689498;
			
			// aapt resource value: 0x7f0f001b
			public const int fill_horizontal = 2131689499;
			
			// aapt resource value: 0x7f0f001c
			public const int fill_vertical = 2131689500;
			
			// aapt resource value: 0x7f0f0014
			public const int fit = 2131689492;
			
			// aapt resource value: 0x7f0f0001
			public const int hybrid = 2131689473;
			
			// aapt resource value: 0x7f0f0006
			public const int icon_only = 2131689478;
			
			// aapt resource value: 0x7f0f0000
			public const int item_touch_helper_previous_elevation = 2131689472;
			
			// aapt resource value: 0x7f0f0010
			public const int left = 2131689488;
			
			// aapt resource value: 0x7f0f000b
			public const int light = 2131689483;
			
			// aapt resource value: 0x7f0f0024
			public const int message = 2131689508;
			
			// aapt resource value: 0x7f0f002e
			public const int myButton = 2131689518;
			
			// aapt resource value: 0x7f0f0002
			public const int none = 2131689474;
			
			// aapt resource value: 0x7f0f0003
			public const int normal = 2131689475;
			
			// aapt resource value: 0x7f0f001e
			public const int parentPanel = 2131689502;
			
			// aapt resource value: 0x7f0f0028
			public const int place_autocomplete_clear_button = 2131689512;
			
			// aapt resource value: 0x7f0f002a
			public const int place_autocomplete_powered_by_google = 2131689514;
			
			// aapt resource value: 0x7f0f002c
			public const int place_autocomplete_prediction_primary_text = 2131689516;
			
			// aapt resource value: 0x7f0f002d
			public const int place_autocomplete_prediction_secondary_text = 2131689517;
			
			// aapt resource value: 0x7f0f002b
			public const int place_autocomplete_progress = 2131689515;
			
			// aapt resource value: 0x7f0f0026
			public const int place_autocomplete_search_button = 2131689510;
			
			// aapt resource value: 0x7f0f0027
			public const int place_autocomplete_search_input = 2131689511;
			
			// aapt resource value: 0x7f0f0029
			public const int place_autocomplete_separator = 2131689513;
			
			// aapt resource value: 0x7f0f0011
			public const int right = 2131689489;
			
			// aapt resource value: 0x7f0f0004
			public const int satellite = 2131689476;
			
			// aapt resource value: 0x7f0f0007
			public const int standard = 2131689479;
			
			// aapt resource value: 0x7f0f001d
			public const int start = 2131689501;
			
			// aapt resource value: 0x7f0f0005
			public const int terrain = 2131689477;
			
			// aapt resource value: 0x7f0f0030
			public const int text = 2131689520;
			
			// aapt resource value: 0x7f0f002f
			public const int title = 2131689519;
			
			// aapt resource value: 0x7f0f0012
			public const int top = 2131689490;
			
			// aapt resource value: 0x7f0f0025
			public const int watch_view_stub = 2131689509;
			
			// aapt resource value: 0x7f0f0008
			public const int wide = 2131689480;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0c0000
			public const int google_play_services_version = 2131492864;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Interpolator
		{
			
			// aapt resource value: 0x7f070000
			public const int generic_confirmation_animation_interpolator_0 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int generic_confirmation_animation_interpolator_1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int generic_confirmation_animation_interpolator_2 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int generic_confirmation_animation_interpolator_3 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int open_on_phone_animation_interpolator_0 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int open_on_phone_animation_interpolator_1 = 2131165189;
			
			static Interpolator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Interpolator()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int alert_dialog_wearable = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int dismiss_overlay = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int error_layout = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int place_autocomplete_fragment = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int place_autocomplete_item_powered_by_google = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int place_autocomplete_item_prediction = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int place_autocomplete_progress = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int RectangleMain = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int RoundMain = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int watch_card_content = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int XFitWatchfaceWearableConfigActivity = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int XFitWatchfaceWearableConfigActivityListItem = 2130968588;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0b0024
			public const int app_name = 2131427364;
			
			// aapt resource value: 0x7f0b001f
			public const int auth_google_play_services_client_facebook_display_name = 2131427359;
			
			// aapt resource value: 0x7f0b001e
			public const int auth_google_play_services_client_google_display_name = 2131427358;
			
			// aapt resource value: 0x7f0b0017
			public const int common_google_play_services_api_unavailable_text = 2131427351;
			
			// aapt resource value: 0x7f0b0009
			public const int common_google_play_services_enable_button = 2131427337;
			
			// aapt resource value: 0x7f0b0008
			public const int common_google_play_services_enable_text = 2131427336;
			
			// aapt resource value: 0x7f0b0007
			public const int common_google_play_services_enable_title = 2131427335;
			
			// aapt resource value: 0x7f0b0006
			public const int common_google_play_services_install_button = 2131427334;
			
			// aapt resource value: 0x7f0b0004
			public const int common_google_play_services_install_text_phone = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int common_google_play_services_install_text_tablet = 2131427333;
			
			// aapt resource value: 0x7f0b0003
			public const int common_google_play_services_install_title = 2131427331;
			
			// aapt resource value: 0x7f0b0012
			public const int common_google_play_services_invalid_account_text = 2131427346;
			
			// aapt resource value: 0x7f0b0011
			public const int common_google_play_services_invalid_account_title = 2131427345;
			
			// aapt resource value: 0x7f0b0010
			public const int common_google_play_services_network_error_text = 2131427344;
			
			// aapt resource value: 0x7f0b000f
			public const int common_google_play_services_network_error_title = 2131427343;
			
			// aapt resource value: 0x7f0b0002
			public const int common_google_play_services_notification_ticker = 2131427330;
			
			// aapt resource value: 0x7f0b001b
			public const int common_google_play_services_restricted_profile_text = 2131427355;
			
			// aapt resource value: 0x7f0b001a
			public const int common_google_play_services_restricted_profile_title = 2131427354;
			
			// aapt resource value: 0x7f0b0019
			public const int common_google_play_services_sign_in_failed_text = 2131427353;
			
			// aapt resource value: 0x7f0b0018
			public const int common_google_play_services_sign_in_failed_title = 2131427352;
			
			// aapt resource value: 0x7f0b0020
			public const int common_google_play_services_unknown_issue = 2131427360;
			
			// aapt resource value: 0x7f0b0014
			public const int common_google_play_services_unsupported_text = 2131427348;
			
			// aapt resource value: 0x7f0b0013
			public const int common_google_play_services_unsupported_title = 2131427347;
			
			// aapt resource value: 0x7f0b0015
			public const int common_google_play_services_update_button = 2131427349;
			
			// aapt resource value: 0x7f0b000b
			public const int common_google_play_services_update_text = 2131427339;
			
			// aapt resource value: 0x7f0b000a
			public const int common_google_play_services_update_title = 2131427338;
			
			// aapt resource value: 0x7f0b000e
			public const int common_google_play_services_updating_text = 2131427342;
			
			// aapt resource value: 0x7f0b000d
			public const int common_google_play_services_updating_title = 2131427341;
			
			// aapt resource value: 0x7f0b000c
			public const int common_google_play_services_wear_update_text = 2131427340;
			
			// aapt resource value: 0x7f0b0016
			public const int common_open_on_phone = 2131427350;
			
			// aapt resource value: 0x7f0b001c
			public const int common_signin_button_text = 2131427356;
			
			// aapt resource value: 0x7f0b001d
			public const int common_signin_button_text_long = 2131427357;
			
			// aapt resource value: 0x7f0b0025
			public const int config_settings = 2131427365;
			
			// aapt resource value: 0x7f0b0021
			public const int dismiss_overlay_button_label = 2131427361;
			
			// aapt resource value: 0x7f0b0022
			public const int hello_rect = 2131427362;
			
			// aapt resource value: 0x7f0b0023
			public const int hello_round = 2131427363;
			
			// aapt resource value: 0x7f0b0001
			public const int place_autocomplete_clear_button = 2131427329;
			
			// aapt resource value: 0x7f0b0000
			public const int place_autocomplete_search_hint = 2131427328;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0e0000
			public const int CardText = 2131623936;
			
			// aapt resource value: 0x7f0e0001
			public const int CardTitle = 2131623937;
			
			// aapt resource value: 0x7f0e0002
			public const int DismissOverlayText = 2131623938;
			
			// aapt resource value: 0x7f0e0003
			public const int DotsPageIndicatorStyle = 2131623939;
			
			// aapt resource value: 0x7f0e000f
			public const int TextAppearance_WearDiag = 2131623951;
			
			// aapt resource value: 0x7f0e0010
			public const int TextAppearance_WearDiag_Button = 2131623952;
			
			// aapt resource value: 0x7f0e0011
			public const int TextAppearance_WearDiag_Message = 2131623953;
			
			// aapt resource value: 0x7f0e0012
			public const int TextAppearance_WearDiag_Title = 2131623954;
			
			// aapt resource value: 0x7f0e0004
			public const int TextAppearance_Wearable_Large = 2131623940;
			
			// aapt resource value: 0x7f0e0005
			public const int TextAppearance_Wearable_Medium = 2131623941;
			
			// aapt resource value: 0x7f0e0006
			public const int TextAppearance_Wearable_Small = 2131623942;
			
			// aapt resource value: 0x7f0e0007
			public const int TextView_Large = 2131623943;
			
			// aapt resource value: 0x7f0e0008
			public const int TextView_Large_Light = 2131623944;
			
			// aapt resource value: 0x7f0e0009
			public const int TextView_Medium = 2131623945;
			
			// aapt resource value: 0x7f0e000a
			public const int TextView_Medium_Light = 2131623946;
			
			// aapt resource value: 0x7f0e000b
			public const int TextView_Small = 2131623947;
			
			// aapt resource value: 0x7f0e000c
			public const int TextView_Small_Light = 2131623948;
			
			// aapt resource value: 0x7f0e0013
			public const int Theme_WearDiag = 2131623955;
			
			// aapt resource value: 0x7f0e000d
			public const int Theme_Wearable = 2131623949;
			
			// aapt resource value: 0x7f0e000e
			public const int Theme_Wearable_Modal = 2131623950;
			
			// aapt resource value: 0x7f0e0014
			public const int Widget_ActionPage = 2131623956;
			
			// aapt resource value: 0x7f0e0015
			public const int Widget_WearDiag_Button = 2131623957;
			
			// aapt resource value: 0x7f0e0016
			public const int Widget_WearDiag_TextView = 2131623958;
			
			// aapt resource value: 0x7f0e0017
			public const int Widget_WearDiag_TextView_Message = 2131623959;
			
			// aapt resource value: 0x7f0e0018
			public const int Widget_WearDiag_TextView_Title = 2131623960;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f080000
			public const int watch_face = 2131230720;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionLabel = new int[]
			{
					16842902,
					16842903,
					16842904,
					16842927,
					16843087,
					16843091,
					16843287,
					16843288,
					16843692,
					2130771991,
					2130771992};
			
			// aapt resource value: 8
			public const int ActionLabel_android_fontFamily = 8;
			
			// aapt resource value: 3
			public const int ActionLabel_android_gravity = 3;
			
			// aapt resource value: 6
			public const int ActionLabel_android_lineSpacingExtra = 6;
			
			// aapt resource value: 7
			public const int ActionLabel_android_lineSpacingMultiplier = 7;
			
			// aapt resource value: 5
			public const int ActionLabel_android_maxLines = 5;
			
			// aapt resource value: 4
			public const int ActionLabel_android_text = 4;
			
			// aapt resource value: 2
			public const int ActionLabel_android_textColor = 2;
			
			// aapt resource value: 1
			public const int ActionLabel_android_textStyle = 1;
			
			// aapt resource value: 0
			public const int ActionLabel_android_typeface = 0;
			
			// aapt resource value: 10
			public const int ActionLabel_maxTextSize = 10;
			
			// aapt resource value: 9
			public const int ActionLabel_minTextSize = 9;
			
			public static int[] ActionPage = new int[]
			{
					16842902,
					16842903,
					16842904,
					16842927,
					16843033,
					16843087,
					16843091,
					16843173,
					16843287,
					16843288,
					16843692,
					16843840,
					16843848,
					2130771991,
					2130771992,
					2130772004,
					2130772005,
					2130772006};
			
			// aapt resource value: 7
			public const int ActionPage_android_color = 7;
			
			// aapt resource value: 11
			public const int ActionPage_android_elevation = 11;
			
			// aapt resource value: 10
			public const int ActionPage_android_fontFamily = 10;
			
			// aapt resource value: 3
			public const int ActionPage_android_gravity = 3;
			
			// aapt resource value: 8
			public const int ActionPage_android_lineSpacingExtra = 8;
			
			// aapt resource value: 9
			public const int ActionPage_android_lineSpacingMultiplier = 9;
			
			// aapt resource value: 6
			public const int ActionPage_android_maxLines = 6;
			
			// aapt resource value: 4
			public const int ActionPage_android_src = 4;
			
			// aapt resource value: 12
			public const int ActionPage_android_stateListAnimator = 12;
			
			// aapt resource value: 5
			public const int ActionPage_android_text = 5;
			
			// aapt resource value: 2
			public const int ActionPage_android_textColor = 2;
			
			// aapt resource value: 1
			public const int ActionPage_android_textStyle = 1;
			
			// aapt resource value: 0
			public const int ActionPage_android_typeface = 0;
			
			// aapt resource value: 16
			public const int ActionPage_buttonRippleColor = 16;
			
			// aapt resource value: 15
			public const int ActionPage_imageScaleMode = 15;
			
			// aapt resource value: 14
			public const int ActionPage_maxTextSize = 14;
			
			// aapt resource value: 13
			public const int ActionPage_minTextSize = 13;
			
			// aapt resource value: 17
			public const int ActionPage_pressedButtonTranslationZ = 17;
			
			public static int[] BoxInsetLayout_Layout = new int[]
			{
					2130771993};
			
			// aapt resource value: 0
			public const int BoxInsetLayout_Layout_layout_box = 0;
			
			public static int[] CircledImageView = new int[]
			{
					16843033,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003};
			
			// aapt resource value: 0
			public const int CircledImageView_android_src = 0;
			
			// aapt resource value: 5
			public const int CircledImageView_circle_border_color = 5;
			
			// aapt resource value: 4
			public const int CircledImageView_circle_border_width = 4;
			
			// aapt resource value: 1
			public const int CircledImageView_circle_color = 1;
			
			// aapt resource value: 6
			public const int CircledImageView_circle_padding = 6;
			
			// aapt resource value: 2
			public const int CircledImageView_circle_radius = 2;
			
			// aapt resource value: 3
			public const int CircledImageView_circle_radius_pressed = 3;
			
			// aapt resource value: 8
			public const int CircledImageView_image_circle_percentage = 8;
			
			// aapt resource value: 9
			public const int CircledImageView_image_horizontal_offcenter_percentage = 9;
			
			// aapt resource value: 10
			public const int CircledImageView_image_tint = 10;
			
			// aapt resource value: 7
			public const int CircledImageView_shadow_width = 7;
			
			public static int[] CircularButton = new int[]
			{
					16843033,
					16843173,
					16843840,
					16843848,
					2130772004,
					2130772005,
					2130772006};
			
			// aapt resource value: 1
			public const int CircularButton_android_color = 1;
			
			// aapt resource value: 2
			public const int CircularButton_android_elevation = 2;
			
			// aapt resource value: 0
			public const int CircularButton_android_src = 0;
			
			// aapt resource value: 3
			public const int CircularButton_android_stateListAnimator = 3;
			
			// aapt resource value: 5
			public const int CircularButton_buttonRippleColor = 5;
			
			// aapt resource value: 4
			public const int CircularButton_imageScaleMode = 4;
			
			// aapt resource value: 6
			public const int CircularButton_pressedButtonTranslationZ = 6;
			
			public static int[] DelayedConfirmationView = new int[]
			{
					2130772007};
			
			// aapt resource value: 0
			public const int DelayedConfirmationView_update_interval = 0;
			
			public static int[] DotsPageIndicator = new int[]
			{
					2130772008,
					2130772009,
					2130772010,
					2130772011,
					2130772012,
					2130772013,
					2130772014,
					2130772015,
					2130772016,
					2130772017,
					2130772018,
					2130772019,
					2130772020};
			
			// aapt resource value: 3
			public const int DotsPageIndicator_dotColor = 3;
			
			// aapt resource value: 4
			public const int DotsPageIndicator_dotColorSelected = 4;
			
			// aapt resource value: 8
			public const int DotsPageIndicator_dotFadeInDuration = 8;
			
			// aapt resource value: 6
			public const int DotsPageIndicator_dotFadeOutDelay = 6;
			
			// aapt resource value: 7
			public const int DotsPageIndicator_dotFadeOutDuration = 7;
			
			// aapt resource value: 5
			public const int DotsPageIndicator_dotFadeWhenIdle = 5;
			
			// aapt resource value: 1
			public const int DotsPageIndicator_dotRadius = 1;
			
			// aapt resource value: 2
			public const int DotsPageIndicator_dotRadiusSelected = 2;
			
			// aapt resource value: 9
			public const int DotsPageIndicator_dotShadowColor = 9;
			
			// aapt resource value: 11
			public const int DotsPageIndicator_dotShadowDx = 11;
			
			// aapt resource value: 12
			public const int DotsPageIndicator_dotShadowDy = 12;
			
			// aapt resource value: 10
			public const int DotsPageIndicator_dotShadowRadius = 10;
			
			// aapt resource value: 0
			public const int DotsPageIndicator_dotSpacing = 0;
			
			public static int[] LoadingImageView = new int[]
			{
					2130771988,
					2130771989,
					2130771990};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] MapAttrs = new int[]
			{
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984};
			
			// aapt resource value: 16
			public const int MapAttrs_ambientEnabled = 16;
			
			// aapt resource value: 1
			public const int MapAttrs_cameraBearing = 1;
			
			// aapt resource value: 2
			public const int MapAttrs_cameraTargetLat = 2;
			
			// aapt resource value: 3
			public const int MapAttrs_cameraTargetLng = 3;
			
			// aapt resource value: 4
			public const int MapAttrs_cameraTilt = 4;
			
			// aapt resource value: 5
			public const int MapAttrs_cameraZoom = 5;
			
			// aapt resource value: 6
			public const int MapAttrs_liteMode = 6;
			
			// aapt resource value: 0
			public const int MapAttrs_mapType = 0;
			
			// aapt resource value: 7
			public const int MapAttrs_uiCompass = 7;
			
			// aapt resource value: 15
			public const int MapAttrs_uiMapToolbar = 15;
			
			// aapt resource value: 8
			public const int MapAttrs_uiRotateGestures = 8;
			
			// aapt resource value: 9
			public const int MapAttrs_uiScrollGestures = 9;
			
			// aapt resource value: 10
			public const int MapAttrs_uiTiltGestures = 10;
			
			// aapt resource value: 11
			public const int MapAttrs_uiZoomControls = 11;
			
			// aapt resource value: 12
			public const int MapAttrs_uiZoomGestures = 12;
			
			// aapt resource value: 13
			public const int MapAttrs_useViewLifecycle = 13;
			
			// aapt resource value: 14
			public const int MapAttrs_zOrderOnTop = 14;
			
			public static int[] ProgressSpinner = new int[]
			{
					2130772021};
			
			// aapt resource value: 0
			public const int ProgressSpinner_color_sequence = 0;
			
			public static int[] RecyclerView = new int[]
			{
					16842948,
					2130772034,
					2130772035,
					2130772036,
					2130772037};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			public static int[] SignInButton = new int[]
			{
					2130771985,
					2130771986,
					2130771987};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			public static int[] WatchViewStub = new int[]
			{
					2130772022,
					2130772023};
			
			// aapt resource value: 0
			public const int WatchViewStub_rectLayout = 0;
			
			// aapt resource value: 1
			public const int WatchViewStub_roundLayout = 1;
			
			public static int[] WearableFrameLayout = new int[]
			{
					16843017,
					16843018,
					16843264,
					16843885,
					2130772024,
					2130772025,
					2130772026,
					2130772027,
					2130772028,
					2130772029,
					2130772030,
					2130772031};
			
			// aapt resource value: 0
			public const int WearableFrameLayout_android_foreground = 0;
			
			// aapt resource value: 2
			public const int WearableFrameLayout_android_foregroundGravity = 2;
			
			// aapt resource value: 3
			public const int WearableFrameLayout_android_foregroundTint = 3;
			
			// aapt resource value: 1
			public const int WearableFrameLayout_android_measureAllChildren = 1;
			
			// aapt resource value: 4
			public const int WearableFrameLayout_layout_gravityRound = 4;
			
			// aapt resource value: 6
			public const int WearableFrameLayout_layout_heightRound = 6;
			
			// aapt resource value: 11
			public const int WearableFrameLayout_layout_marginBottomRound = 11;
			
			// aapt resource value: 8
			public const int WearableFrameLayout_layout_marginLeftRound = 8;
			
			// aapt resource value: 10
			public const int WearableFrameLayout_layout_marginRightRound = 10;
			
			// aapt resource value: 7
			public const int WearableFrameLayout_layout_marginRound = 7;
			
			// aapt resource value: 9
			public const int WearableFrameLayout_layout_marginTopRound = 9;
			
			// aapt resource value: 5
			public const int WearableFrameLayout_layout_widthRound = 5;
			
			public static int[] WearableHeaderTextView = new int[]
			{
					2130772032,
					2130772033};
			
			// aapt resource value: 0
			public const int WearableHeaderTextView_circular_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int WearableHeaderTextView_circular_text_size = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
