#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XFitWatchface.Resource", IsApplication=true)]

namespace XFitWatchface
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int buttonSize = 2130771972;
			
			// aapt resource value: 0x7f010009
			public const int circleCrop = 2130771977;
			
			// aapt resource value: 0x7f010005
			public const int colorScheme = 2130771973;
			
			// aapt resource value: 0x7f010008
			public const int imageAspectRatio = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int imageAspectRatioAdjust = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int scopeUris = 2130771974;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070008
			public const int common_action_bar_splitter = 2131165192;
			
			// aapt resource value: 0x7f070011
			public const int common_google_signin_btn_text_dark = 2131165201;
			
			// aapt resource value: 0x7f070009
			public const int common_google_signin_btn_text_dark_default = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int common_google_signin_btn_text_dark_disabled = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int common_google_signin_btn_text_dark_focused = 2131165196;
			
			// aapt resource value: 0x7f07000a
			public const int common_google_signin_btn_text_dark_pressed = 2131165194;
			
			// aapt resource value: 0x7f070012
			public const int common_google_signin_btn_text_light = 2131165202;
			
			// aapt resource value: 0x7f07000d
			public const int common_google_signin_btn_text_light_default = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int common_google_signin_btn_text_light_disabled = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int common_google_signin_btn_text_light_focused = 2131165200;
			
			// aapt resource value: 0x7f07000e
			public const int common_google_signin_btn_text_light_pressed = 2131165198;
			
			// aapt resource value: 0x7f070013
			public const int common_plus_signin_btn_text_dark = 2131165203;
			
			// aapt resource value: 0x7f070000
			public const int common_plus_signin_btn_text_dark_default = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int common_plus_signin_btn_text_dark_disabled = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int common_plus_signin_btn_text_dark_focused = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int common_plus_signin_btn_text_dark_pressed = 2131165185;
			
			// aapt resource value: 0x7f070014
			public const int common_plus_signin_btn_text_light = 2131165204;
			
			// aapt resource value: 0x7f070004
			public const int common_plus_signin_btn_text_light_default = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int common_plus_signin_btn_text_light_disabled = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int common_plus_signin_btn_text_light_focused = 2131165191;
			
			// aapt resource value: 0x7f070005
			public const int common_plus_signin_btn_text_light_pressed = 2131165189;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_ic_googleplayservices = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_plus_signin_btn_icon_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_plus_signin_btn_icon_dark_focused = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_light_disabled = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_light_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_text_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_text_dark_disabled = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_text_dark_focused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_light_disabled = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_light_focused = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_pressed = 2130837545;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int adjust_height = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int adjust_width = 2131099656;
			
			// aapt resource value: 0x7f060004
			public const int auto = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int dark = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int icon_only = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int item_touch_helper_previous_elevation = 2131099648;
			
			// aapt resource value: 0x7f060006
			public const int light = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int myButton = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int none = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int standard = 2131099650;
			
			// aapt resource value: 0x7f06000b
			public const int stepCountCheckbox = 2131099659;
			
			// aapt resource value: 0x7f060003
			public const int wide = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int google_play_services_version = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int XFitWatchfaceCompanionConfigActivity = 2130968577;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080020
			public const int app_name = 2131230752;
			
			// aapt resource value: 0x7f08001d
			public const int auth_google_play_services_client_facebook_display_name = 2131230749;
			
			// aapt resource value: 0x7f08001c
			public const int auth_google_play_services_client_google_display_name = 2131230748;
			
			// aapt resource value: 0x7f080015
			public const int common_google_play_services_api_unavailable_text = 2131230741;
			
			// aapt resource value: 0x7f080007
			public const int common_google_play_services_enable_button = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int common_google_play_services_enable_text = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int common_google_play_services_enable_title = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int common_google_play_services_install_button = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int common_google_play_services_install_text_phone = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int common_google_play_services_install_text_tablet = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int common_google_play_services_install_title = 2131230721;
			
			// aapt resource value: 0x7f080010
			public const int common_google_play_services_invalid_account_text = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int common_google_play_services_invalid_account_title = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int common_google_play_services_network_error_text = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int common_google_play_services_network_error_title = 2131230733;
			
			// aapt resource value: 0x7f080000
			public const int common_google_play_services_notification_ticker = 2131230720;
			
			// aapt resource value: 0x7f080019
			public const int common_google_play_services_restricted_profile_text = 2131230745;
			
			// aapt resource value: 0x7f080018
			public const int common_google_play_services_restricted_profile_title = 2131230744;
			
			// aapt resource value: 0x7f080017
			public const int common_google_play_services_sign_in_failed_text = 2131230743;
			
			// aapt resource value: 0x7f080016
			public const int common_google_play_services_sign_in_failed_title = 2131230742;
			
			// aapt resource value: 0x7f08001e
			public const int common_google_play_services_unknown_issue = 2131230750;
			
			// aapt resource value: 0x7f080012
			public const int common_google_play_services_unsupported_text = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int common_google_play_services_unsupported_title = 2131230737;
			
			// aapt resource value: 0x7f080013
			public const int common_google_play_services_update_button = 2131230739;
			
			// aapt resource value: 0x7f080009
			public const int common_google_play_services_update_text = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int common_google_play_services_update_title = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int common_google_play_services_updating_text = 2131230732;
			
			// aapt resource value: 0x7f08000b
			public const int common_google_play_services_updating_title = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int common_google_play_services_wear_update_text = 2131230730;
			
			// aapt resource value: 0x7f080014
			public const int common_open_on_phone = 2131230740;
			
			// aapt resource value: 0x7f08001a
			public const int common_signin_button_text = 2131230746;
			
			// aapt resource value: 0x7f08001b
			public const int common_signin_button_text_long = 2131230747;
			
			// aapt resource value: 0x7f08001f
			public const int hello = 2131230751;
			
			// aapt resource value: 0x7f080021
			public const int stepCountCheckbox = 2131230753;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] RecyclerView = new int[]
			{
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			public static int[] SignInButton = new int[]
			{
					2130771972,
					2130771973,
					2130771974};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
