#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("SQLCipherApp.Resource", IsApplication=true)]

namespace SQLCipherApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues ();
		}
		
		public static void UpdateIdValues()
		{
			Mono.Data.Sqlcipher.Resource.String.library_name = SQLCipherApp.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int buttonSave = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int buttonSend = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int editTextMessage = 2131034112;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040005
			public const int buttonSave = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int buttonSend = 2130968582;
			
			// aapt resource value: 0x7f040002
			public const int hintEmail = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int hintMessage = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int hintPassword = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
