#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AndroidPlayerMiniHack.Resource", IsApplication=true)]

namespace AndroidPlayerMiniHack
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int cardview_dark_background = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int cardview_light_background = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int cardview_shadow_end_color = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int cardview_shadow_start_color = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050000
			public const int cardview_default_radius = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cardview_elevation = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int cardview_shadow_size = 2131034114;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int caterpiller = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int flying_in_the_light_large = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int jelly_fish_2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int lone_pine_sunset = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int look_me_in_the_eye = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int over_there = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int rainbow = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int sample1 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int sample2 = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int battery_level = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int battery_status = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int compass_layout = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int imageView = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int recycler_view = 2131230724;
			
			// aapt resource value: 0x7f080002
			public const int refresh_battery = 2131230722;
			
			// aapt resource value: 0x7f080006
			public const int textView = 2131230726;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int recycleritem_card = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int refresh_battery = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int CardView = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int CardView_Dark = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int CardView_Light = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[]
			{
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int CardView_cardBackgroundColor = 0;
			
			// aapt resource value: 1
			public const int CardView_cardCornerRadius = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
