#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("XFitWatchface.Resource", IsApplication=true)]

namespace XFitWatchface
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int generic_confirmation_generic_confirmation_animation = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int generic_confirmation_icon_animation = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int open_on_phone_arrow_animation = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int open_on_phone_path_1_animation = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int open_on_phone_path_2_animation = 2131034116;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f060000
			public const int circular_image_button_anim = 2131099648;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090000
			public const int progress_spinner_sequence = 2131296256;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f01000e
			public const int buttonRippleColor = 2130771982;
			
			// aapt resource value: 0x7f010007
			public const int circle_border_color = 2130771975;
			
			// aapt resource value: 0x7f010006
			public const int circle_border_width = 2130771974;
			
			// aapt resource value: 0x7f010003
			public const int circle_color = 2130771971;
			
			// aapt resource value: 0x7f010008
			public const int circle_padding = 2130771976;
			
			// aapt resource value: 0x7f010004
			public const int circle_radius = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int circle_radius_pressed = 2130771973;
			
			// aapt resource value: 0x7f010029
			public const int circular_layout_gravity = 2130772009;
			
			// aapt resource value: 0x7f01002a
			public const int circular_text_size = 2130772010;
			
			// aapt resource value: 0x7f01001e
			public const int color_sequence = 2130771998;
			
			// aapt resource value: 0x7f010014
			public const int dotColor = 2130771988;
			
			// aapt resource value: 0x7f010015
			public const int dotColorSelected = 2130771989;
			
			// aapt resource value: 0x7f010019
			public const int dotFadeInDuration = 2130771993;
			
			// aapt resource value: 0x7f010017
			public const int dotFadeOutDelay = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int dotFadeOutDuration = 2130771992;
			
			// aapt resource value: 0x7f010016
			public const int dotFadeWhenIdle = 2130771990;
			
			// aapt resource value: 0x7f010012
			public const int dotRadius = 2130771986;
			
			// aapt resource value: 0x7f010013
			public const int dotRadiusSelected = 2130771987;
			
			// aapt resource value: 0x7f01001a
			public const int dotShadowColor = 2130771994;
			
			// aapt resource value: 0x7f01001c
			public const int dotShadowDx = 2130771996;
			
			// aapt resource value: 0x7f01001d
			public const int dotShadowDy = 2130771997;
			
			// aapt resource value: 0x7f01001b
			public const int dotShadowRadius = 2130771995;
			
			// aapt resource value: 0x7f010011
			public const int dotSpacing = 2130771985;
			
			// aapt resource value: 0x7f01000d
			public const int imageScaleMode = 2130771981;
			
			// aapt resource value: 0x7f01000a
			public const int image_circle_percentage = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int image_horizontal_offcenter_percentage = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int image_tint = 2130771980;
			
			// aapt resource value: 0x7f01002b
			public const int layoutManager = 2130772011;
			
			// aapt resource value: 0x7f010002
			public const int layout_box = 2130771970;
			
			// aapt resource value: 0x7f010021
			public const int layout_gravityRound = 2130772001;
			
			// aapt resource value: 0x7f010023
			public const int layout_heightRound = 2130772003;
			
			// aapt resource value: 0x7f010028
			public const int layout_marginBottomRound = 2130772008;
			
			// aapt resource value: 0x7f010025
			public const int layout_marginLeftRound = 2130772005;
			
			// aapt resource value: 0x7f010027
			public const int layout_marginRightRound = 2130772007;
			
			// aapt resource value: 0x7f010024
			public const int layout_marginRound = 2130772004;
			
			// aapt resource value: 0x7f010026
			public const int layout_marginTopRound = 2130772006;
			
			// aapt resource value: 0x7f010022
			public const int layout_widthRound = 2130772002;
			
			// aapt resource value: 0x7f010001
			public const int maxTextSize = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int minTextSize = 2130771968;
			
			// aapt resource value: 0x7f01000f
			public const int pressedButtonTranslationZ = 2130771983;
			
			// aapt resource value: 0x7f01001f
			public const int rectLayout = 2130771999;
			
			// aapt resource value: 0x7f01002d
			public const int reverseLayout = 2130772013;
			
			// aapt resource value: 0x7f010020
			public const int roundLayout = 2130772000;
			
			// aapt resource value: 0x7f010009
			public const int shadow_width = 2130771977;
			
			// aapt resource value: 0x7f01002c
			public const int spanCount = 2130772012;
			
			// aapt resource value: 0x7f01002e
			public const int stackFromEnd = 2130772014;
			
			// aapt resource value: 0x7f010010
			public const int update_interval = 2130771984;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f0a0021
			public const int ColorItemCircleBorderColor = 2131361825;
			
			// aapt resource value: 0x7f0a0020
			public const int ColorItemLabelColor = 2131361824;
			
			// aapt resource value: 0x7f0a001c
			public const int ConfigActivityBackground = 2131361820;
			
			// aapt resource value: 0x7f0a001f
			public const int ConfigActivityCircleBorderColor = 2131361823;
			
			// aapt resource value: 0x7f0a001d
			public const int ConfigActivityHeaderTextColor = 2131361821;
			
			// aapt resource value: 0x7f0a001e
			public const int ConfigActivityItemLabelColor = 2131361822;
			
			// aapt resource value: 0x7f0a0000
			public const int action_button_background = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int black = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int black_54p = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int black_86p = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int blue = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int card_default_background = 2131361797;
			
			// aapt resource value: 0x7f0a0022
			public const int circular_button = 2131361826;
			
			// aapt resource value: 0x7f0a0006
			public const int circular_button_disabled = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int circular_button_normal = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int circular_button_pressed = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int dark_blue = 2131361801;
			
			// aapt resource value: 0x7f0a000a
			public const int dark_grey = 2131361802;
			
			// aapt resource value: 0x7f0a000b
			public const int dark_red = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int dialog_background = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int dialog_shade_background = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int disabled_text_light = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int dismiss_close = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int dismiss_close_pressed = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int dismiss_overlay_bg = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int green = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int grey = 2131361811;
			
			// aapt resource value: 0x7f0a0014
			public const int light_grey = 2131361812;
			
			// aapt resource value: 0x7f0a0015
			public const int orange = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int primary_text_dark = 2131361814;
			
			// aapt resource value: 0x7f0a0017
			public const int primary_text_light = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int red = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int secondary_text_light = 2131361817;
			
			// aapt resource value: 0x7f0a001a
			public const int semitransparent_grey = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int white = 2131361819;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0b0013
			public const int ContentPaddingStart = 2131427347;
			
			// aapt resource value: 0x7f0b0012
			public const int StepCountOffset = 2131427346;
			
			// aapt resource value: 0x7f0b0011
			public const int StepCountTextSize = 2131427345;
			
			// aapt resource value: 0x7f0b0000
			public const int card_content_padding_rect_top = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int circular_button_elevation = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int circular_button_elevation_pressed = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int close_button_diameter = 2131427331;
			
			// aapt resource value: 0x7f0b0004
			public const int diag_button_bottom_padding = 2131427332;
			
			// aapt resource value: 0x7f0b0005
			public const int diag_button_bottom_padding_round = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int diag_button_side_padding_right_round = 2131427334;
			
			// aapt resource value: 0x7f0b0007
			public const int diag_content_bottom_padding = 2131427335;
			
			// aapt resource value: 0x7f0b0008
			public const int diag_content_side_padding = 2131427336;
			
			// aapt resource value: 0x7f0b0009
			public const int diag_content_side_padding_round = 2131427337;
			
			// aapt resource value: 0x7f0b000a
			public const int diag_content_top_padding = 2131427338;
			
			// aapt resource value: 0x7f0b000b
			public const int diag_content_top_padding_round = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public const int diag_floating_height = 2131427340;
			
			// aapt resource value: 0x7f0b000d
			public const int diag_shade_height_rect = 2131427341;
			
			// aapt resource value: 0x7f0b000e
			public const int diag_shade_height_round = 2131427342;
			
			// aapt resource value: 0x7f0b000f
			public const int dismiss_padding = 2131427343;
			
			// aapt resource value: 0x7f0b0010
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131427344;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int card_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int card_frame = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int card_frame_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int close_button = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int generic_confirmation = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int generic_confirmation_animation = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_full_cancel = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_full_sad = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int open_on_phone = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int open_on_phone_animation = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int preview_xfit = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int XamarinWatchFaceBackground = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0e0013
			public const int alertTitle = 2131623955;
			
			// aapt resource value: 0x7f0e0001
			public const int all = 2131623937;
			
			// aapt resource value: 0x7f0e0012
			public const int animatedWrapperContainer = 2131623954;
			
			// aapt resource value: 0x7f0e0002
			public const int bottom = 2131623938;
			
			// aapt resource value: 0x7f0e0014
			public const int buttonPanel = 2131623956;
			
			// aapt resource value: 0x7f0e0006
			public const int center = 2131623942;
			
			// aapt resource value: 0x7f0e0008
			public const int center_horizontal = 2131623944;
			
			// aapt resource value: 0x7f0e0009
			public const int center_vertical = 2131623945;
			
			// aapt resource value: 0x7f0e000a
			public const int clip_horizontal = 2131623946;
			
			// aapt resource value: 0x7f0e000b
			public const int clip_vertical = 2131623947;
			
			// aapt resource value: 0x7f0e0016
			public const int dismiss_overlay_button = 2131623958;
			
			// aapt resource value: 0x7f0e0015
			public const int dismiss_overlay_explain = 2131623957;
			
			// aapt resource value: 0x7f0e000c
			public const int end = 2131623948;
			
			// aapt resource value: 0x7f0e000d
			public const int fill = 2131623949;
			
			// aapt resource value: 0x7f0e000e
			public const int fill_horizontal = 2131623950;
			
			// aapt resource value: 0x7f0e000f
			public const int fill_vertical = 2131623951;
			
			// aapt resource value: 0x7f0e0007
			public const int fit = 2131623943;
			
			// aapt resource value: 0x7f0e0000
			public const int item_touch_helper_previous_elevation = 2131623936;
			
			// aapt resource value: 0x7f0e0003
			public const int left = 2131623939;
			
			// aapt resource value: 0x7f0e0017
			public const int message = 2131623959;
			
			// aapt resource value: 0x7f0e0019
			public const int myButton = 2131623961;
			
			// aapt resource value: 0x7f0e0011
			public const int parentPanel = 2131623953;
			
			// aapt resource value: 0x7f0e0004
			public const int right = 2131623940;
			
			// aapt resource value: 0x7f0e0010
			public const int start = 2131623952;
			
			// aapt resource value: 0x7f0e001b
			public const int text = 2131623963;
			
			// aapt resource value: 0x7f0e001a
			public const int title = 2131623962;
			
			// aapt resource value: 0x7f0e0005
			public const int top = 2131623941;
			
			// aapt resource value: 0x7f0e0018
			public const int watch_view_stub = 2131623960;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Interpolator
		{
			
			// aapt resource value: 0x7f070000
			public const int generic_confirmation_animation_interpolator_0 = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int generic_confirmation_animation_interpolator_1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int generic_confirmation_animation_interpolator_2 = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int generic_confirmation_animation_interpolator_3 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int open_on_phone_animation_interpolator_0 = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int open_on_phone_animation_interpolator_1 = 2131165189;
			
			static Interpolator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Interpolator()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int alert_dialog_wearable = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int dismiss_overlay = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int error_layout = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Main = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int RectangleMain = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int RoundMain = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int watch_card_content = 2130968582;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0c0003
			public const int app_name = 2131492867;
			
			// aapt resource value: 0x7f0c0004
			public const int config_settings = 2131492868;
			
			// aapt resource value: 0x7f0c0000
			public const int dismiss_overlay_button_label = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int hello_rect = 2131492865;
			
			// aapt resource value: 0x7f0c0002
			public const int hello_round = 2131492866;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0d0000
			public const int CardText = 2131558400;
			
			// aapt resource value: 0x7f0d0001
			public const int CardTitle = 2131558401;
			
			// aapt resource value: 0x7f0d0002
			public const int DismissOverlayText = 2131558402;
			
			// aapt resource value: 0x7f0d0003
			public const int DotsPageIndicatorStyle = 2131558403;
			
			// aapt resource value: 0x7f0d000f
			public const int TextAppearance_WearDiag = 2131558415;
			
			// aapt resource value: 0x7f0d0010
			public const int TextAppearance_WearDiag_Button = 2131558416;
			
			// aapt resource value: 0x7f0d0011
			public const int TextAppearance_WearDiag_Message = 2131558417;
			
			// aapt resource value: 0x7f0d0012
			public const int TextAppearance_WearDiag_Title = 2131558418;
			
			// aapt resource value: 0x7f0d0004
			public const int TextAppearance_Wearable_Large = 2131558404;
			
			// aapt resource value: 0x7f0d0005
			public const int TextAppearance_Wearable_Medium = 2131558405;
			
			// aapt resource value: 0x7f0d0006
			public const int TextAppearance_Wearable_Small = 2131558406;
			
			// aapt resource value: 0x7f0d0007
			public const int TextView_Large = 2131558407;
			
			// aapt resource value: 0x7f0d0008
			public const int TextView_Large_Light = 2131558408;
			
			// aapt resource value: 0x7f0d0009
			public const int TextView_Medium = 2131558409;
			
			// aapt resource value: 0x7f0d000a
			public const int TextView_Medium_Light = 2131558410;
			
			// aapt resource value: 0x7f0d000b
			public const int TextView_Small = 2131558411;
			
			// aapt resource value: 0x7f0d000c
			public const int TextView_Small_Light = 2131558412;
			
			// aapt resource value: 0x7f0d0013
			public const int Theme_WearDiag = 2131558419;
			
			// aapt resource value: 0x7f0d000d
			public const int Theme_Wearable = 2131558413;
			
			// aapt resource value: 0x7f0d000e
			public const int Theme_Wearable_Modal = 2131558414;
			
			// aapt resource value: 0x7f0d0014
			public const int Widget_ActionPage = 2131558420;
			
			// aapt resource value: 0x7f0d0015
			public const int Widget_WearDiag_Button = 2131558421;
			
			// aapt resource value: 0x7f0d0016
			public const int Widget_WearDiag_TextView = 2131558422;
			
			// aapt resource value: 0x7f0d0017
			public const int Widget_WearDiag_TextView_Message = 2131558423;
			
			// aapt resource value: 0x7f0d0018
			public const int Widget_WearDiag_TextView_Title = 2131558424;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f080000
			public const int watch_face = 2131230720;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ActionLabel = new int[]
			{
					16842902,
					16842903,
					16842904,
					16842927,
					16843087,
					16843091,
					16843287,
					16843288,
					16843692,
					2130771968,
					2130771969};
			
			// aapt resource value: 8
			public const int ActionLabel_android_fontFamily = 8;
			
			// aapt resource value: 3
			public const int ActionLabel_android_gravity = 3;
			
			// aapt resource value: 6
			public const int ActionLabel_android_lineSpacingExtra = 6;
			
			// aapt resource value: 7
			public const int ActionLabel_android_lineSpacingMultiplier = 7;
			
			// aapt resource value: 5
			public const int ActionLabel_android_maxLines = 5;
			
			// aapt resource value: 4
			public const int ActionLabel_android_text = 4;
			
			// aapt resource value: 2
			public const int ActionLabel_android_textColor = 2;
			
			// aapt resource value: 1
			public const int ActionLabel_android_textStyle = 1;
			
			// aapt resource value: 0
			public const int ActionLabel_android_typeface = 0;
			
			// aapt resource value: 10
			public const int ActionLabel_maxTextSize = 10;
			
			// aapt resource value: 9
			public const int ActionLabel_minTextSize = 9;
			
			public static int[] ActionPage = new int[]
			{
					16842902,
					16842903,
					16842904,
					16842927,
					16843033,
					16843087,
					16843091,
					16843173,
					16843287,
					16843288,
					16843692,
					16843840,
					16843848,
					2130771968,
					2130771969,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 7
			public const int ActionPage_android_color = 7;
			
			// aapt resource value: 11
			public const int ActionPage_android_elevation = 11;
			
			// aapt resource value: 10
			public const int ActionPage_android_fontFamily = 10;
			
			// aapt resource value: 3
			public const int ActionPage_android_gravity = 3;
			
			// aapt resource value: 8
			public const int ActionPage_android_lineSpacingExtra = 8;
			
			// aapt resource value: 9
			public const int ActionPage_android_lineSpacingMultiplier = 9;
			
			// aapt resource value: 6
			public const int ActionPage_android_maxLines = 6;
			
			// aapt resource value: 4
			public const int ActionPage_android_src = 4;
			
			// aapt resource value: 12
			public const int ActionPage_android_stateListAnimator = 12;
			
			// aapt resource value: 5
			public const int ActionPage_android_text = 5;
			
			// aapt resource value: 2
			public const int ActionPage_android_textColor = 2;
			
			// aapt resource value: 1
			public const int ActionPage_android_textStyle = 1;
			
			// aapt resource value: 0
			public const int ActionPage_android_typeface = 0;
			
			// aapt resource value: 16
			public const int ActionPage_buttonRippleColor = 16;
			
			// aapt resource value: 15
			public const int ActionPage_imageScaleMode = 15;
			
			// aapt resource value: 14
			public const int ActionPage_maxTextSize = 14;
			
			// aapt resource value: 13
			public const int ActionPage_minTextSize = 13;
			
			// aapt resource value: 17
			public const int ActionPage_pressedButtonTranslationZ = 17;
			
			public static int[] BoxInsetLayout_Layout = new int[]
			{
					2130771970};
			
			// aapt resource value: 0
			public const int BoxInsetLayout_Layout_layout_box = 0;
			
			public static int[] CircledImageView = new int[]
			{
					16843033,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 0
			public const int CircledImageView_android_src = 0;
			
			// aapt resource value: 5
			public const int CircledImageView_circle_border_color = 5;
			
			// aapt resource value: 4
			public const int CircledImageView_circle_border_width = 4;
			
			// aapt resource value: 1
			public const int CircledImageView_circle_color = 1;
			
			// aapt resource value: 6
			public const int CircledImageView_circle_padding = 6;
			
			// aapt resource value: 2
			public const int CircledImageView_circle_radius = 2;
			
			// aapt resource value: 3
			public const int CircledImageView_circle_radius_pressed = 3;
			
			// aapt resource value: 8
			public const int CircledImageView_image_circle_percentage = 8;
			
			// aapt resource value: 9
			public const int CircledImageView_image_horizontal_offcenter_percentage = 9;
			
			// aapt resource value: 10
			public const int CircledImageView_image_tint = 10;
			
			// aapt resource value: 7
			public const int CircledImageView_shadow_width = 7;
			
			public static int[] CircularButton = new int[]
			{
					16843033,
					16843173,
					16843840,
					16843848,
					2130771981,
					2130771982,
					2130771983};
			
			// aapt resource value: 1
			public const int CircularButton_android_color = 1;
			
			// aapt resource value: 2
			public const int CircularButton_android_elevation = 2;
			
			// aapt resource value: 0
			public const int CircularButton_android_src = 0;
			
			// aapt resource value: 3
			public const int CircularButton_android_stateListAnimator = 3;
			
			// aapt resource value: 5
			public const int CircularButton_buttonRippleColor = 5;
			
			// aapt resource value: 4
			public const int CircularButton_imageScaleMode = 4;
			
			// aapt resource value: 6
			public const int CircularButton_pressedButtonTranslationZ = 6;
			
			public static int[] DelayedConfirmationView = new int[]
			{
					2130771984};
			
			// aapt resource value: 0
			public const int DelayedConfirmationView_update_interval = 0;
			
			public static int[] DotsPageIndicator = new int[]
			{
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997};
			
			// aapt resource value: 3
			public const int DotsPageIndicator_dotColor = 3;
			
			// aapt resource value: 4
			public const int DotsPageIndicator_dotColorSelected = 4;
			
			// aapt resource value: 8
			public const int DotsPageIndicator_dotFadeInDuration = 8;
			
			// aapt resource value: 6
			public const int DotsPageIndicator_dotFadeOutDelay = 6;
			
			// aapt resource value: 7
			public const int DotsPageIndicator_dotFadeOutDuration = 7;
			
			// aapt resource value: 5
			public const int DotsPageIndicator_dotFadeWhenIdle = 5;
			
			// aapt resource value: 1
			public const int DotsPageIndicator_dotRadius = 1;
			
			// aapt resource value: 2
			public const int DotsPageIndicator_dotRadiusSelected = 2;
			
			// aapt resource value: 9
			public const int DotsPageIndicator_dotShadowColor = 9;
			
			// aapt resource value: 11
			public const int DotsPageIndicator_dotShadowDx = 11;
			
			// aapt resource value: 12
			public const int DotsPageIndicator_dotShadowDy = 12;
			
			// aapt resource value: 10
			public const int DotsPageIndicator_dotShadowRadius = 10;
			
			// aapt resource value: 0
			public const int DotsPageIndicator_dotSpacing = 0;
			
			public static int[] ProgressSpinner = new int[]
			{
					2130771998};
			
			// aapt resource value: 0
			public const int ProgressSpinner_color_sequence = 0;
			
			public static int[] RecyclerView = new int[]
			{
					16842948,
					2130772011,
					2130772012,
					2130772013,
					2130772014};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			public static int[] WatchViewStub = new int[]
			{
					2130771999,
					2130772000};
			
			// aapt resource value: 0
			public const int WatchViewStub_rectLayout = 0;
			
			// aapt resource value: 1
			public const int WatchViewStub_roundLayout = 1;
			
			public static int[] WearableFrameLayout = new int[]
			{
					16843017,
					16843018,
					16843264,
					16843885,
					2130772001,
					2130772002,
					2130772003,
					2130772004,
					2130772005,
					2130772006,
					2130772007,
					2130772008};
			
			// aapt resource value: 0
			public const int WearableFrameLayout_android_foreground = 0;
			
			// aapt resource value: 2
			public const int WearableFrameLayout_android_foregroundGravity = 2;
			
			// aapt resource value: 3
			public const int WearableFrameLayout_android_foregroundTint = 3;
			
			// aapt resource value: 1
			public const int WearableFrameLayout_android_measureAllChildren = 1;
			
			// aapt resource value: 4
			public const int WearableFrameLayout_layout_gravityRound = 4;
			
			// aapt resource value: 6
			public const int WearableFrameLayout_layout_heightRound = 6;
			
			// aapt resource value: 11
			public const int WearableFrameLayout_layout_marginBottomRound = 11;
			
			// aapt resource value: 8
			public const int WearableFrameLayout_layout_marginLeftRound = 8;
			
			// aapt resource value: 10
			public const int WearableFrameLayout_layout_marginRightRound = 10;
			
			// aapt resource value: 7
			public const int WearableFrameLayout_layout_marginRound = 7;
			
			// aapt resource value: 9
			public const int WearableFrameLayout_layout_marginTopRound = 9;
			
			// aapt resource value: 5
			public const int WearableFrameLayout_layout_widthRound = 5;
			
			public static int[] WearableHeaderTextView = new int[]
			{
					2130772009,
					2130772010};
			
			// aapt resource value: 0
			public const int WearableHeaderTextView_circular_layout_gravity = 0;
			
			// aapt resource value: 1
			public const int WearableHeaderTextView_circular_text_size = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
