// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Amqp.Lite.iOS {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SRAmqp {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SRAmqp() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Amqp.Lite.iOS.SRAmqp", typeof(SRAmqp).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string AmqpChannelNotFound {
            get {
                return ResourceManager.GetString("AmqpChannelNotFound", resourceCulture);
            }
        }
        
        internal static string AmqpHandleExceeded {
            get {
                return ResourceManager.GetString("AmqpHandleExceeded", resourceCulture);
            }
        }
        
        internal static string AmqpHandleNotFound {
            get {
                return ResourceManager.GetString("AmqpHandleNotFound", resourceCulture);
            }
        }
        
        internal static string AmqpHandleInUse {
            get {
                return ResourceManager.GetString("AmqpHandleInUse", resourceCulture);
            }
        }
        
        internal static string AmqpIllegalOperationState {
            get {
                return ResourceManager.GetString("AmqpIllegalOperationState", resourceCulture);
            }
        }
        
        internal static string AmqpInvalidFormatCode {
            get {
                return ResourceManager.GetString("AmqpInvalidFormatCode", resourceCulture);
            }
        }
        
        internal static string AmqpOperationNotSupported {
            get {
                return ResourceManager.GetString("AmqpOperationNotSupported", resourceCulture);
            }
        }
        
        internal static string AmqpTimeout {
            get {
                return ResourceManager.GetString("AmqpTimeout", resourceCulture);
            }
        }
        
        internal static string AmqpUnknownDescriptor {
            get {
                return ResourceManager.GetString("AmqpUnknownDescriptor", resourceCulture);
            }
        }
        
        internal static string DeliveryLimitExceeded {
            get {
                return ResourceManager.GetString("DeliveryLimitExceeded", resourceCulture);
            }
        }
        
        internal static string EncodingTypeNotSupported {
            get {
                return ResourceManager.GetString("EncodingTypeNotSupported", resourceCulture);
            }
        }
        
        internal static string InvalidAddressFormat {
            get {
                return ResourceManager.GetString("InvalidAddressFormat", resourceCulture);
            }
        }
        
        internal static string InvalidDeliveryIdOnTransfer {
            get {
                return ResourceManager.GetString("InvalidDeliveryIdOnTransfer", resourceCulture);
            }
        }
        
        internal static string InvalidFrameSize {
            get {
                return ResourceManager.GetString("InvalidFrameSize", resourceCulture);
            }
        }
        
        internal static string InvalidMapCount {
            get {
                return ResourceManager.GetString("InvalidMapCount", resourceCulture);
            }
        }
        
        internal static string InvalidMapKeyType {
            get {
                return ResourceManager.GetString("InvalidMapKeyType", resourceCulture);
            }
        }
        
        internal static string InvalidSequenceNumberComparison {
            get {
                return ResourceManager.GetString("InvalidSequenceNumberComparison", resourceCulture);
            }
        }
        
        internal static string LinkNotFound {
            get {
                return ResourceManager.GetString("LinkNotFound", resourceCulture);
            }
        }
        
        internal static string SaslNegoFailed {
            get {
                return ResourceManager.GetString("SaslNegoFailed", resourceCulture);
            }
        }
        
        internal static string WindowViolation {
            get {
                return ResourceManager.GetString("WindowViolation", resourceCulture);
            }
        }
    }
}
